import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Accordion } from "../ui/Accordion";
import { Select } from "../ui/Select";
import { Switch } from "../ui/Switch";
import { Input } from "../ui/Input";
export function PolicyCard({ policy, onChange, errors = {} }) {
    return (_jsx(Accordion, { title: "Policy", defaultOpen: true, tone: "muted", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-text", htmlFor: "auth-mode", children: "Auth mode" }), _jsxs(Select, { id: "auth-mode", value: policy.authMode, hasError: Boolean(errors["policy.authMode"]), onChange: (e) => onChange({ ...policy, authMode: e.target.value }), children: [_jsx("option", { value: "required", children: "Required" }), _jsx("option", { value: "optional", children: "Optional" }), _jsx("option", { value: "none", children: "None" })] }), errors["policy.authMode"] ? (_jsx("p", { className: "text-xs text-error", role: "alert", children: errors["policy.authMode"] })) : (_jsx("p", { className: "text-xs text-textMuted", children: "Required means students must sign in; optional allows anonymous." }))] }), _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-text", children: "Require view code" }), _jsx("p", { className: "text-xs text-textMuted", children: "Students must enter a code to load questions." })] }), _jsx(Switch, { id: "require-view-code", checked: policy.requireViewCode, onChange: (value) => onChange({ ...policy, requireViewCode: value }) })] }), _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-text", children: "Require submit code" }), _jsx("p", { className: "text-xs text-textMuted", children: "Students must enter a code to submit answers." })] }), _jsx(Switch, { id: "require-submit-code", checked: policy.requireSubmitCode, onChange: (value) => onChange({ ...policy, requireSubmitCode: value }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-text", htmlFor: "solutions-mode", children: "Solutions mode" }), _jsxs(Select, { id: "solutions-mode", value: policy.solutionsMode, hasError: Boolean(errors["policy.solutionsMode"]), onChange: (e) => onChange({ ...policy, solutionsMode: e.target.value }), children: [_jsx("option", { value: "never", children: "Never" }), _jsx("option", { value: "after_submit", children: "After submit" }), _jsx("option", { value: "always", children: "Always" })] }), errors["policy.solutionsMode"] ? (_jsx("p", { className: "text-xs text-error", role: "alert", children: errors["policy.solutionsMode"] })) : (_jsx("p", { className: "text-xs text-textMuted", children: "Controls when answer keys and solutions become visible." }))] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-text", htmlFor: "time-limit-minutes", children: "Time limit (minutes)" }), _jsx(Input, { id: "time-limit-minutes", type: "number", value: policy.timeLimitMinutes ?? "", onChange: (e) => onChange({
                                ...policy,
                                timeLimitMinutes: e.target.value ? Number(e.target.value) : undefined
                            }), placeholder: "Optional", hasError: Boolean(errors["policy.timeLimitMinutes"]) }), errors["policy.timeLimitMinutes"] ? (_jsx("p", { className: "text-xs text-error", role: "alert", children: errors["policy.timeLimitMinutes"] })) : (_jsx("p", { className: "text-xs text-textMuted", children: "Leave blank for no time limit." }))] })] }) }));
}
